networks:
  airflow-net:
    driver: bridge
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow-log
      POSTGRES_PASSWORD: O&*TG^78tyu
      POSTGRES_DB: airflow-log
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/dataports
    ports:
      - "5432:5432"
    networks:
      - airflow-net

  spark-master:
      build:
        context: ./Docker/spark-master
        # dockerfile: ./Docker/spark-master/Dockerfile
      # image: apache/spark-py
      container_name: spark-master
      hostname: spark-master
      environment:
        - SPARK_MODE=master
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_MASTER_HOST=spark-master
      ports:
        - "8080:8080"
        - "7077:7077"
      volumes:
        - ./spark_events:/opt/spark/events
        - ./jars:/opt/spark/jars
      networks:
        - airflow-net
      command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master > /opt/spark/logs/master.log 2>&1
      # /opt/spark/sbin/start-master.sh

  spark-worker:
      build:
        context: ./Docker/spark-worker
        # dockerfile: ./Docker/spark-worker/Dockerfile
      # image: apache/spark-py
      container_name: spark-worker
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
      depends_on:
        - spark-master
      volumes:
        - ./spark_events:/opt/spark/events
        - ./jars:/opt/spark/jars
      networks:
        - airflow-net
      command: >
        /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  airflow:
    build:
      context: ./Docker/airflow
      # dockerfile: ./Docker/airflow/Dockerfile
    image: apache/airflow:2.8.1
    container_name: airflow
    depends_on:
      - postgres
      - spark-master
    environment:
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow-log:O&*TG^78tyu@postgres:5432/airflow-log"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8090"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./spark_events:/opt/spark/events
    ports:
      - "8090:8090"
    command: >
      bash -c "
      airflow db init && \
      airflow connections add 'spark_standalone_client' \
      --conn-json '{\"conn_type\": \"spark\", \"host\": \"spark://spark-master\", \"port\": 7077}' && \
      airflow users create --username admin --password admin --firstname Bernardo --lastname Pereira --role Admin --email admin@local && \
      airflow webserver"
    networks:
      - airflow-net
      
  scheduler:
    image: apache/airflow:2.7.1
    container_name: scheduler
    depends_on:
      - postgres
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Bernardo --lastname Pereira --role Admin --email admin@example.com && airflow webserver"
    environment:
      - AIRFLOW_DATABASE_SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow-log:O&*TG^78tyu@postgres/airflow-log
      - EXECUTOR=LocalExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs

volumes:
  postgres_data:
  spark_events: